version: '3'

services:

  app:
    image: olgapj/devops-for-programmers-project-74
    build:
      context: .
      dockerfile: Dockerfile.production
    command: 
      - make prepare-env
      - npm test
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}

